services:

  documentacion:
    restart: always
    build: .   # 'Dockerfile' en la ruta actual de archivo
    ports:
      - ${PUERTO_MKDOCS:-9003}:8000
    security_opt: 
      - label=disable
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true


  fastapi-test:
    restart: always
    build: tests/fastapi/
    ports:
      - ${PUERTO_FASTAPI:-9001}:8000


  flet-test:
    restart: always
    build: tests/flet/
    ports:
      - ${PUERTO_FLET:-9002}:8000



  postgres-test:
    restart: always
    image: postgres:17.2-bookworm 
    shm_size: 128mb 
    environment:
      POSTGRES_PASSWORD:  "123456"
      POSTGRES_USER:      "postgres"
      POSTGRES_DB:        "test-db"
    ports:
      - ${PUERTO_POSTGRES:-9000}:5432
    volumes:
      - 'db-test-data:/var/lib/postgresql/data'


volumes:
  db-test-data:
    # external: true