site_name: Banco Devops


site_url: https://PYTHON-DESDE-0.github.io/banco-devops
site_description: Despliegue para el proyecto de sistema bancario

# Repositorio
repo_url: https://github.com/PYTHON-DESDE-0/banco-devops
repo_name: banco-devops
# edit_uri: edit/master/docs/

# copyright: Copyright &copy; 2025

# ruta a los documentos
docs_dir: documentacion/


theme:
  name: material
  icon: 
    # logo: fontawesome/solid/user-nurse
    annotation: material/arrow-right-circle
    logo: material/bank  # :material-bank:
    # Icono de repositorio
    repo: fontawesome/brands/github

  language: es
  # Modos para la pagina
  palette:
    # Modo automático
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Cambia al modo claro
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb  
        name: Cambia al modo oscuro
      primary: blue grey
      accent: blue
    # Modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Cambia al modo automático
      primary: blue grey
      accent: blue

  features:
    - header.autohide
    - navigation.footerq
    # - navigation.instant
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - search
    - search.suggest
    - search.highlight
    - search.share
    - search:
      lang: es
    - toc.follow
    - navigation.top  # boton emergente para volver al inicio  - aparece al intentar subir con el scroll

    - navigation.instant
    - navigation.instant.progress   # progreso de carga (conexiones lentas)
    - navigation.tracking
    # pestañas de contenido
    - navigation.tabs
    # pie de navegacion
    - navigation.footer
    # - navigation.tabs.sticky
    # - navigation.sections   # Muestra títulos para los contenidos en la barra izquierda
    # - navigation.expand     # Expansión - Expande la lista de contenidos por defecto
    # - navigation.prune      # Poda - Quita la lista de contenidos no visibles
    - navigation.indexes    # Permite agregar varios archivos a una sección



    # header y anuncios
    - header.autohide
    - announce.dismiss



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


plugins: 
  - privacy
  - search

  # fechas de repositorio
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: date        # fecha
      fallback_to_build_date: true
  # contribuyentes
  - git-committers:
      repository: nombre_usuario/nombre_repositorio
      branch: master      # rama a seguir
      enabled: true
        
  - group:
      enabled: !ENV CI
      plugins:
      # # blog (todo)
      # - blog:
      #     # blog_dir: .
      #     enabled: true
      #     blog_dir: blog    # cambia la carpeta del blog
      #     post_dir: "{blog}/posts"   # cambia la carpeta de los posts
      #     # barra de contenido 
      #     blog_toc: true
      #     post_date_format: short
      #     post_url_date_format: yyyy/MM/dd
      #     # borradores 
      #     draft: true                   # habilita ver borradores  
      #     draft_on_serve: true           # borradores disponibles en preview
      #     draft_if_future_date: true      # si la fecha es futura se considera borrador
      #     # archive_pagination_per_page: 2
      #     categories: true    # Incluye ordenamiento por categorias
      #     categories_name:    Categorias
      #     post_url_format: "{date}/{slug}"
      #     post_url_max_categories: 2
      #     archive: true    # listado de entradas habilitado - más recientes primero
      #     archive_name: Archivo 
      #     archive_date_format:  MMMM yyyy
      #     archive_url_date_format: yyyy/MM
      #     archive_url_format: "archivo/{date}"
      #     # calculo automatico de tiempos de lectura
      #     post_readtime: false
      #     post_readtime_words_per_minute: 300    # tasa de lectura estimada
      #     # separador de resumen - cuerpo de cada post
      #     post_excerpt: optional
      #     post_excerpt_separator: <!-- mas -->
      # # soporte para RSS (depende del blog)
      # - rss:
      #     match_path: "blog/posts/.*"
      #     date_from_meta:
      #       as_creation: date.created
      #       as_update: date.updated
      # Tarjetas PNG automáticas 
      - social:
          cards_layout: default/accent

  # - tags:
  #     tags_file: tags.md


nav:
  - Introducción: index.md
  - Despliegue:
    # - General:
    - despliegue/consideraciones.md
    - Componentes:
      - componentes/index.md
      - componentes/entorno.md
      - componentes/venv.md
      - componentes/sqlmodel.md



    - Despliegue:
    # - Contenedores:
      - despliegue/index.md
      # - despliegue/intro.md
      - despliegue/imagenes.md
      - despliegue/python.md
      - despliegue/postgres.md
    - Borradores:
      - despliegue/adicionales.md
      - borradores/servidores.md
      - despliegue/tips.md

      - borradores/mkdocs.md

    - despliegue/pruebas.md

